version: "3"

services:
    api:
        image: api
        deploy:
            restart_policy:
                condition: any
        ports:
            - 5000:5000
        environment:
            - INCV3_HOST=incv3:9000
            - FASH_HOST=fash:9000
    incv3:
        image: epigramai/model-server:light
        command: ["--port=9000", "--model_name=incv3", "--model_base_path=/models/incv3_bottleneck"]
        deploy:
            restart_policy:
                condition: any
        volumes:
            - ./models:/models/
    fash:
        image: epigramai/model-server:light
        command: ["--port=9000", "--model_name=fashion", "--model_base_path=/models/final_layers"]
        deploy:
            restart_policy:
                condition: any
        volumes:
            - ./models:/models/