version: "3"

services:
    api:
        image: epigramai/tfserving-api-test:x
        deploy:
            restart_policy:
                condition: any
        ports:
            - 5000:5000
        environment:
            - INCV4_HOST=incv4:9000
    incv4:
        image: epigramai/model-server:light
        command: ["--port=9000", "--model_name=incv4", "--model_base_path=/models/incv4_1536"]
        deploy:
            restart_policy:
                condition: any
        volumes:
            - ./models:/models/