version: "3"

services:
    api:
        image: epigramai/tfserving-api-test:latest
        deploy:
            restart_policy:
                condition: any
        ports:
            - 5000:5000
        environment:
            - MNIST_HOST=mnist
            - MNIST_PORT=9000
    mnist:
        image: epigramai/model-server:serve
        command: ["--port=9000", "--model_name=mnist", "--model_base_path=models/mnist_cnn"]
        deploy:
            restart_policy:
                condition: any
        volumes:
            - /Users/slp/Development/tfserving/models:/models/
